### ISSUE TITLE
Please test pyhf v0.7.0 release candidates

### ISSUE THREAD

**Issue by matthewfeickert** [Rupt/interval-evidence#1]
Hi. :wave: As you're a user of `pyhf`

https://github.com/Rupt/interval-evidence/blob/d66d1a12620826497f6a9a4e64321a596ed834e7/requirements.txt#L1-L10

please test the [`pyhf` `v0.7.0` release candidates](https://github.com/scikit-hep/pyhf/releases/tag/v0.7.0rc4) to see if you will be affected by any of the API changes.

```
python -m pip install --upgrade --pre pyhf
```

If you haven't yet, please also consider joining the [pyhf-announcements mailing list](https://groups.google.com/group/pyhf-announcements/subscribe).

**Comment by Rupt** [comment]
Hi @matthewfeickert

As you comment quotes, this repository is already using the release candidate `pyhf[minuit]==0.7.0rc1`.

I would prefer not to receive such issues in future. Closing.

**Comment by matthewfeickert** [comment]
> As you comment quotes, this repository is already using the release candidate `pyhf[minuit]==0.7.0rc1`.

There are more recent release candiates.

> I would prefer not to receive such issues in future

Noted. You won't hear from us again.
